---
- name: Include base packages installation
  ansible.builtin.include_tasks: base_packages.yml
  when: install_base_packages | default(true)

- name: Include system configuration
  ansible.builtin.include_tasks: system_config.yml
  when: install_base_packages | default(true)

- name: Include RKE2 prerequisites installation
  ansible.builtin.include_tasks: rke2_prerequisites.yml
  when: install_rke2_prerequisites | default(true)

- name: Include Helm installation
  ansible.builtin.include_tasks: helm.yml
  when: install_helm | default(true)

- name: Include cleanup tasks
  ansible.builtin.include_tasks: cleanup.yml
