---
# Default variables for image preparation role
rke2_version: v1.33.4+rke2r1  # https://github.com/rancher/rke2/tags
helm_version: v3.18.6  # https://github.com/helm/helm/tags

# System packages to install (Ubuntu focused)
base_packages:
  - python3
  - python3-pip
  - python3-openshift
  - nfs-common
  - curl
  - wget
  - unzip
  - tar
  - git
  - jq
  - vim
  - gnupg
  - ca-certificates

# Enable/disable components
install_base_packages: true
install_cvmfs: true
install_rke2_prerequisites: true
install_helm: true
install_docker: true
